# Input dimension of camera
IMAGE_HEIGHT = 80
IMAGE_WIDTH = 160
IMAGE_DEPTH = 3
INPUT_DIM = (IMAGE_HEIGHT, IMAGE_WIDTH, IMAGE_DEPTH)

MAX_STEERING = 1
MIN_STEERING = -MAX_STEERING

MIN_THROTTLE = 0.5
MAX_THROTTLE = 0.2
REWARD_CRASH = -10
CRASH_SPEED_WEIGHT = 5
THROTTLE_REWARD_WEIGHT = 0.1

